
version: "3.8"

volumes:
  sqlite_data:
  backend_database:

networks:
  ft_transcendence-network:  # Custom internal network

services:

  backend:
    container_name: ft_transcendence-backend
    image: ft_transcendence-backend:latest
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "5555:5555" # Prisma Studio
    env_file:
      - backend/.env
    volumes:
        - sqlite_data:/database
        - ./backend/prisma:/app/prisma  # Prisma schema available
    networks:
      - ft_transcendence-network
    entrypoint: ["/app/entrypoint.sh"] # Uses script to handle DB migrations
    healthcheck:
      test: ["CMD", "sh", "-c", "/app/healthcheck.sh"]
      interval: 10s
      retries: 5
  
  frontend:
    container_name: ft_transcendence-frontend
    image: ft_transcendence-frontend:latest
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    depends_on:
      - backend
      # backend:
      #   condition: service_healthy  # Wait until backend is ready
    ports:
      - "5000:80" # Serve frontend on port 5000 via Nginx
    networks:
      - ft_transcendence-network
    volumes:
    - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro # Mount custom Nginx config
