
version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - backend/.env
    restart: always

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "5173:5173"
    restart: always

  game:
    build:
      context: .
      dockerfile: docker/game.Dockerfile
    ports:
      - "8080:8080"
    restart: always

  database:
    image: "sqlite"
    volumes:
      - sqlite_data:/database
    restart: always

volumes:
  sqlite_data:
