
version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    env_file:
      - backend/.env
    command: npm run dev

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: npm run dev

  game:
    build:
      context: .
      dockerfile: docker/game.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./game:/app
    command: npm run dev

  database:
    image: "sqlite"
    volumes:
      - sqlite_data:/database

volumes:
  sqlite_data:
