# File: docker-compose.yml

version: "3.8"

networks:
  catpong_network:

volumes:
  backend_uploads:
  backend_data:
  nginx_certs:

services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - JWT_SECRET=${JWT_SECRET:-supersecretkey}
    volumes:
      - backend_uploads:/app/uploads
      - backend_data:/app/data
    networks:
      - catpong_network

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    depends_on:
      - backend
    networks:
      - catpong_network

  nginx:
    build:
      context: .
      dockerfile: nginx/nginx.Dockerfile
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    environment:
      - DOMAIN=${DOMAIN:-localhost}
    volumes:
      - nginx_certs:/etc/nginx/ssl
    depends_on:
      - backend
    networks:
      - catpong_network
