
version: "3.8"

networks:
  ft_transcendence-network:
    driver: bridge

volumes:
  sqlite_data:

services:

  backend:
    container_name: ft_transcendence-backend
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    # env_file:
      # - backend/.env
    environment:
      DATABASE_URL: ${DATABASE_URL:-sqlite://./database/data.db}
      JWT_SECRET: ${JWT_SECRET:-default_secret}
      NODE_ENV: ${NODE_ENV:-development}
    ports:
      - "3000:3000"
      - "5555:5555" # Prisma Studio
    volumes:
      - sqlite_data:/database
    networks:
      - ft_transcendence-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "/app/healthcheck.sh"]
      interval: 10s
      retries: 5
  
  frontend:
    container_name: ft_transcendence-frontend
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    networks:
      - ft_transcendence-network
    restart: unless-stopped
    depends_on:
      - backend
      # backend:
      #   condition: service_healthy  # Wait until backend is ready

  nginx:
    container_name: ft_transcendence-nginx
    build:
      context: .
      dockerfile: deployments/nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - ft_transcendence-network
    depends_on:
      - frontend
      - backend
    restart: unless-stopped


# TOCHOOSE: (backend would then depend on this container)
  # sqlite:
  #   container_name: ft_transcendence-sqlite
  #   build:
  #     context: 
  #     dockerfile: 
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - sqlite_data:/database
  #   networks:
  #     - ft_transcendence-network
  #   restart: always
