
version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    ports:
      - "3000:3000"
    volumes:
      - ../backend:/app
    command: ["sh", "-c", "npx prisma migrate deploy && node server.js"]
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:/app/database.sqlite
