
# Use latest PHP image
FROM php:8.1-cli

# Set working directory
WORKDIR /app

# Copy backend files
COPY ./backend/ /app/

# Expose WebSocket server port
EXPOSE 8080

# Start WebSocket server
CMD ["php", "server.php"]
