services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.php
    container_name: php_backend
    restart: always
    volumes:
      - ./backend:/var/www/html
    ports:
      - "9000:9000"

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.front
    container_name: ts_frontend
    restart: always
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"

  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ft_transcendence
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  websocket:
    build:
      context: .
      dockerfile: docker/Dockerfile.websocket
    container_name: php_websocket
    restart: always
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8081:8081"

volumes:
  db_data:
